name: Compilar APK de Kivy

# Esto hace que el bot trabaje cada vez que modificas un archivo
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias de Linux y Buildozer
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install --user --upgrade buildozer cython virtualenv

      - name: Compilar la App a APK
        run: |
          # El comando "yes" acepta automáticamente las licencias de Android
          yes | buildozer android debug

      - name: Guardar y subir el APK
        uses: actions/upload-artifact@v4
        with:
          name: App-Bluetooth-APK
          path: bin/*.apk
