name: Compilar APK de Kivy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Descargar el c√≥digo
        uses: actions/checkout@v4

      - name: Configurar Java 17 para Gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias de Linux y Buildozer
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install --user --upgrade buildozer "Cython==0.29.33" virtualenv

      - name: Compilar la App a APK
        run: |
          yes | buildozer android debug

      - name: Guardar y subir el APK
        uses: actions/upload-artifact@v4
        with:
          name: App-Compartir-APK
          path: bin/*.apk
